export const blogList = [
  {
    id: 1,
    title: 'Descriptive Event Name Title One Featured',
    dateStart: 'May 15, 2023',
    dateEnd: 'May 30, 2023',
    category: 'development',
    subCategory: ['frontend', 'ui/ux', 'design'],
    contactInfo: 'For more information, contact ',
    contactName: 'John Doe',
    contactEmail: 'jon.doe@company.com',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/hero.jpg',
  },
  {
    id: 2,
    title: 'Descriptive Event Name Title Two',
    dateStart: 'April 15, 2023',
    dateEnd: 'April 30, 2023',
    category: 'travel',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    contactInfo: 'For more information, contact ',
    contactName: 'John Doe',
    contactEmail: 'jon.doe@company.com',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/hero.jpg',
  },
  {
    id: 3,
    title: 'Descriptive Event Name Title Three',
    dateStart: 'April 15, 2023',
    dateEnd: 'April 30, 2023',
    category: 'shopping',
    subCategory: ['e-commerce store', 'clothing', 'shopping store'],
    contactInfo: 'For more information, contact ',
    contactName: 'John Doe',
    contactEmail: 'jon.doe@company.com',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/hero.jpg',
  },
  {
    id: 4,
    title: 'Descriptive Event Name Title Four',
    dateStart: 'April 15, 2023',
    dateEnd: 'April 30, 2023',
    contactInfo: 'For more information, contact ',
    contactName: 'John Doe',
    contactEmail: 'jon.doe@company.com',
    category: 'adventure',
    subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/hero.jpg',
  },
  {
    id: 5,
    title: 'Descriptive Event Name Title Five',
    dateStart: 'April 15, 2023',
    dateEnd: 'April 30, 2023',
    category: 'cooking',
    subCategory: ['bbq', 'food', 'lifestyle'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/hero.jpg',
  },
  {
    id: 6,
    title: 'Descriptive Event Name Title Six',
    dateStart: 'April 15, 2023',
    dateEnd: 'April 30, 2023',
    category: 'travel',
    subCategory: ['beaches', 'sea', 'holidays'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/hero.jpg',
  },
  {
    id: 7,
    title: 'Descriptive Event Name Title Seven',
    dateStart: 'April 15, 2023',
    dateEnd: 'April 30, 2023',
    category: 'art',
    subCategory: ['skill', 'design', 'passion'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/hero.jpg',
  },
];
